# Site settings
title: Susan Su
tagline: 'A personal site'
description: 'a wandering dot'
url: https://suasn.live
baseurl: ''

# About/contact
author:
  name: Susan Su
  url: https://suasn.live

# Permalinks
permalink: pretty

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Build settings
markdown: kramdown
highlighter: rouge

# Gems/Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Exclude files
exclude:
  - README.md
  - LICENSE.md
  - .gitignore

# GitHub Pages specific
github: [metadata]
